USE master;
GO

CREATE LOGIN DB_PRIMARY
   WITH PASSWORD = '1qaz@WSX3edc';
GO

CREATE USER DB_PRIMARY_user FOR LOGIN DB_PRIMARY;
GO

CREATE CERTIFICATE DB_PRIMARY
   AUTHORIZATION DB_PRIMARY_user
   FROM FILE = 'D:\CERTIFICATE_bak\DB_PRIMARY_cert.cer'
GO

GRANT CONNECT ON ENDPOINT::Endpoint_DB_BACKUP TO DB_PRIMARY;
GO

/*****************************/

ALTER DATABASE idc_data
    SET PARTNER = 'TCP://10.20.2.3:5022';
GO

/*
ALTER DATABASE idc_mirror_test SET PARTNER SUSPEND;

ALTER DATABASE idc_mirror_test SET PARTNER RESUME;

ALTER DATABASE idc_mirror_test SET PARTNER OFF;
*/