--ASC
DECLARE 
	@STIME DATETIME = '2022-06-01 00:00:00.000',
	@ETIME DATETIME = '2022-08-01 00:00:00.000',
	@SCHEME VARCHAR(20) = 'Psh_dlt',
	@FUNCTION VARCHAR(20) = 'Pfn_datetime_dlt',
	@FILEGROUP VARCHAR(20) = 'FG_DLT_BASE',
	@SQL NVARCHAR(500),
	@Type INT = 2

WHILE (@STIME < @ETIME)
BEGIN
	
	SET @SQL = 
	CASE @Type 
	WHEN 1 THEN 'ALTER PARTITION SCHEME ' + QUOTENAME(@SCHEME,'') + ' NEXT USED ' + QUOTENAME(@FILEGROUP,'') + ' ; ALTER PARTITION FUNCTION ' + QUOTENAME(@FUNCTION,'') + '() SPLIT RANGE (' + QUOTENAME(CONVERT(VARCHAR(25),@STIME,120),'''') + ');'	
	WHEN 2 THEN 'ALTER PARTITION FUNCTION ' + QUOTENAME(@FUNCTION,'') + '() MERGE RANGE (' + QUOTENAME(CONVERT(VARCHAR(25),@STIME,120),'''') + ')'
	END

	SPL:
	BEGIN TRY
		--EXEC (@SQL)
		RAISERROR(@SQL,0,1) WITH NOWAIT;	
	END TRY
	BEGIN CATCH
		--PRINT ERROR_MESSAGE()
		GOTO SPL
	END CATCH

	SET @STIME = DATEADD(DAY,1,@STIME)
END
GO

--DESC
DECLARE 
	@STIME DATETIME = '2022-06-24 00:00:00.000',
	@ETIME DATETIME = '2022-04-01 00:00:00.000',
	@SCHEME VARCHAR(20) = 'Psh_dlt',
	@FUNCTION VARCHAR(20) = 'Pfn_datetime_dlt',
	@FILEGROUP VARCHAR(20) = 'FG_DLT_BASE',
	@SQL NVARCHAR(500),
	@Type INT = 1

WHILE (@STIME >= @ETIME)
BEGIN
	
	SET @SQL = 
	CASE @Type 
	WHEN 1 THEN 'ALTER PARTITION SCHEME ' + QUOTENAME(@SCHEME,'') + ' NEXT USED ' + QUOTENAME(@FILEGROUP,'') + ' ; ALTER PARTITION FUNCTION ' + QUOTENAME(@FUNCTION,'') + '() SPLIT RANGE (' + QUOTENAME(CONVERT(VARCHAR(25),@STIME,120),'''') + ');'	
	WHEN 2 THEN 'ALTER PARTITION FUNCTION ' + QUOTENAME(@FUNCTION,'') + '() MERGE RANGE (' + QUOTENAME(CONVERT(VARCHAR(25),@STIME,120),'''') + ')'
	END

	SPL:
	BEGIN TRY
		--EXEC (@SQL)
		RAISERROR(@SQL,0,1) WITH NOWAIT;	
	END TRY
	BEGIN CATCH
		PRINT ERROR_MESSAGE()
		GOTO SPL
	END CATCH

	SET @STIME = DATEADD(DAY,-1,@STIME)
END