
/***Server Master Key***/
CREATE MASTER KEY ENCRYPTION BY PASSWORD = '1qaz@WSX';
GO

/***CREATE CERTIFICATE***/
CREATE CERTIFICATE BACKUP_CERTIFICATE_BO
WITH SUBJECT = 'Database Backup Certificate';  
GO

/***BACKUP CERTIFICATE**/
BACKUP CERTIFICATE BACKUP_CERTIFICATE_BO TO FILE = 'D:\CERTIFICATE\BACKUP_CERTIFICATE_BO.cert'
WITH PRIVATE KEY (
FILE = 'D:\CERTIFICATE\BACKUP_CERTIFICATE_BO.key',
ENCRYPTION BY PASSWORD = '1qaz@WSX')
GO

/***備份選項***/
BACKUP DATABASE main_db TO DISK = 'D:\BAK\main_db_full.bak'
WITH ENCRYPTION (ALGORITHM = AES_256,SERVER CERTIFICATE = BACKUP_CERTIFICATE_BO),
NAME = N'main_db-Diff Database Backup', SKIP, NOREWIND, NOUNLOAD,
COMPRESSION, STATS = 10

BACKUP DATABASE main_db TO DISK = 'D:\BAK\main_db_diff.bak'
WITH ENCRYPTION (ALGORITHM = AES_256,SERVER CERTIFICATE = BACKUP_CERTIFICATE_BO),
NAME = N'main_db-Diff Database Backup', SKIP, NOREWIND, NOUNLOAD, DIFFERENTIAL,
COMPRESSION, STATS = 10

BACKUP LOG main_db TO DISK = 'D:\BAK\main_db_log.bak'
WITH ENCRYPTION (ALGORITHM = AES_256,SERVER CERTIFICATE = BACKUP_CERTIFICATE_BO),
NAME = N'main_db-Diff Database Backup', SKIP, NOREWIND, NOUNLOAD,
COMPRESSION, STATS = 10

--其他Server還原DB
--1.CREATE MASTER KEY
--2.CERTIFICATE （p.s.憑證路徑需放入此資料夾下）
CREATE CERTIFICATE BACKUP_CERTIFICATE_BO
FROM FILE = 'D:\CERTIFICATE\BACKUP_CERTIFICATE_BO.cert'
WITH PRIVATE KEY (FILE = 'D:\CERTIFICATE\BACKUP_CERTIFICATE_BO.key',
DECRYPTION BY PASSWORD = '1qaz@WSX');


--3.正常還原