USE master;
GO

CREATE LOGIN DB_BACKUP_MIRROR
   WITH PASSWORD = '1qaz@WSX3edc';
GO

CREATE USER DB_BACKUP_MIRROR_user FOR LOGIN DB_BACKUP_MIRROR;
GO

CREATE CERTIFICATE DB_BACKUP_MIRROR
   AUTHORIZATION DB_BACKUP_MIRROR_user
   FROM FILE = 'D:\CERTIFICATE_bak\DB_BACKUP_cert.cer'
GO

GRANT CONNECT ON ENDPOINT::Endpoint_DB_PRIMARY TO DB_BACKUP_MIRROR;
GO

/*****************************/

ALTER DATABASE idc_data 
    SET PARTNER = 'TCP://10.20.2.2:5022';
GO

/*
ALTER DATABASE idc_data SET PARTNER OFF;  

ALTER DATABASE idc_mirror_test SET PARTNER SUSPEND;

ALTER DATABASE idc_mirror_test SET PARTNER RESUME;
*/